#!/usr/bin/env bash

START_PATH="$PWD"

input=`cat ../_input/"$1"`
# echo "$START_PATH"

cd src

[ "$2" = 1 ] && part="one"
[ "$2" = 2 ] && part="two"

./Husk -uf "$START_PATH"/"$1"/"part_$part".husk "$input"

cd $START_PATH