#!/bin/env bash

# ./run 01 1

[ "$2" = 1 ] && part="one"
[ "$2" = 2 ] && part="two"

input=`cat ../../_input/2021/"$1"/"$3"`

cd "$1"

if [[ -n "$input" ]]
then
  echo "$input" | raku "part_$part".raku
else
  echo "input file empty"
  exit 69
fi

cd ..